[package]
name = "omicron-package"
version = "0.1.0"
edition = "2018"
license = "MPL-2.0"

[dependencies]
anyhow = "1.0"
crossbeam = "0.8"
flate2 = "1.0.22"
rayon = "1.5"
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls"] }
serde = { version = "1.0", features = [ "derive" ] }
serde_derive = "1.0"
smf = "0.2"
structopt = "0.3"
tar = "0.4"
tempfile = "3.3"
thiserror = "1.0"
tokio = { version = "1.17", features = [ "full" ] }
toml = "0.5.6"
walkdir = "2.3"
